### ISSUE TITLE
リスト全表示

### ISSUE THREAD

**Issue by yukFuruya** [yukFuruya/TsMemo#23]

**Comment by hirooop** [comment]
カレンダーの日付をタップすると、その日付に対応する日記の内容が下半分に出るようにしたい。

まずは全ての日付の全ての投稿を下半分に表示するようにする。
次に、その投稿を選択した日付でフィルタして狙った日付だけ出せるようにする。

**Comment by yukFuruya** [comment]
- [ ] DiaryItem.tsxでそれぞれのDiaryの表示の詳細を決める
- [ ] firebase.tsでfirebaseからデータを取ってくる処理を書く
- [ ] 表示したい画面.tsxでFlatlistを追加する
- [ ] fetchDiaryとかでfirebaseのデータを取ってくる受口の処理を書く
